version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: luxe-hotel-app
    container_name: luxe-hotel-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: hotel_booking
      DB_USERNAME: hotel_user
      DB_PASSWORD: root
    command: php artisan serve --host=0.0.0.0

  db:
    image: mysql:8.0
    container_name: luxe-hotel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hotel_booking
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: hotel_user
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: luxe-hotel-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  dbdata:
    driver: local 